import getProfileImg from "@/app/services/profile/getRandomImg"

const imgSRC = await getProfileImg()

export const commentArray = [
  {
    id: 1,
    parentId: null,
    content: "Finally! Season 2 of No Game No Life is real?! This is not a drill!",
    author: "Goffy Uzusaki",
    profileImage: imgSRC,
    likes: [101, 202, 303],
    dislike: [404],
    createdAt: "2025-05-20T10:30:00Z",
  },
  {
    id: 2,
    parentId: 1,
    content: "Been waiting for this moment since 2014. Let’s gooo!",
    author: "Mina Kuro",
    profileImage: imgSRC,
    likes: [303],
    dislike: [],
    createdAt: "2025-05-20T10:45:00Z",
  },
  {
    id: 3,
    parentId: 1,
    content: "Hope it's not just a recap or troll trailer 😭",
    author: "DarkSenpai",
    profileImage: imgSRC,
    likes: [202],
    dislike: [101],
    createdAt: "2025-05-20T11:00:00Z",
  },
  {
    id: 4,
    parentId: 2,
    content: "Same! I rewatched season 1 like 4 times already. I need new content!",
    author: "Aiko Blaze",
    profileImage: imgSRC,
    likes: [202, 303],
    dislike: [],
    createdAt: "2025-05-20T11:15:00Z",
  },
  {
    id: 5,
    parentId: 3,
    content: "Nah it's confirmed legit this time. Studio MADHOUSE themselves dropped the news.",
    author: "OtakuKage",
    profileImage: imgSRC,
    likes: [101, 404],
    dislike: [],
    createdAt: "2025-05-20T11:30:00Z",
  },
  {
    id: 6,
    parentId: null,
    content: "Anyone know if the original voice actors are returning?",
    author: "SakuraSky",
    profileImage: imgSRC,
    likes: [202],
    dislike: [],
    createdAt: "2025-05-20T11:45:00Z",
  },
  {
    id: 7,
    parentId: 6,
    content: "Yup! Same cast, same vibe. Hype is real 😎",
    author: "NovaChan",
    profileImage: imgSRC,
    likes: [101, 303],
    dislike: [],
    createdAt: "2025-05-20T12:00:00Z",
  },
  {
    id: 8,
    parentId: null,
    content: "Still mad we never got season 2 of Deadman Wonderland tho...",
    author: "GrimByte",
    profileImage: imgSRC,
    likes: [404],
    dislike: [],
    createdAt: "2025-05-20T12:10:00Z",
  },
]