export const suggestionData = [
  { id: 1, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-season-2-5647#ep=12' },
  { id: 2, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-5647#ep=12' },
  { id: 3, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/moonrise-season-2-5647#ep=12' },
  { id: 4, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/naruto-5647#ep=12' },
  { id: 5, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-season-2-5647#ep=12' },
  { id: 6, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-season-2-5647#ep=12' },
  { id: 7, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-season-2-5647#ep=12' },
  { id: 1, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-season-2-5647#ep=12' },
  { id: 2, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-5647#ep=12' },
  { id: 3, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/moonrise-season-2-5647#ep=12' },
  { id: 4, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/naruto-5647#ep=12' },
  { id: 5, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-season-2-5647#ep=12' },
  { id: 6, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-season-2-5647#ep=12' },
  { id: 7, title: 'SOme Gibberish i Found Online', imgURL: 'http://localhost:5000/static/shonen-1.jpg', episode: '12 Episode', link: '/watch/fire-force-season-2-5647#ep=12' },
]